# Generated by Django 3.2.6 on 2021-08-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='scrapeData',
            fields=[
                ('dataId', models.AutoField(primary_key=True, serialize=False)),
                ('dataTitle', models.CharField(max_length=20)),
                ('dataTime', models.CharField(max_length=20)),
                ('dataLink', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'scrapeData',
            },
        ),
    ]
